### ISSUE TITLE
Can not make it work with Amp IDE

### ISSUE THREAD

**Issue by damianpdr** [heyhuynhgiabuu/proxypal#14]
I've tried to change amp URL in amp IDE in vscode to: http://localhost:8317 or http://localhost:8317/v1 but nothing works, when im trying to send a message i see : "Invalid API key Open Settings to set or update your Amp API key."

AMP cli working perfectly with the proxy

**Comment by heyhuynhgiabuu** [comment]
## ✅ Issue Resolved

The AMP IDE extension integration issue has been fixed!

### Root Cause
CLIProxyAPI was configured with `restrict-management-to-localhost: true`, which blocked browser-based requests from VSCode extensions. The AMP CLI worked fine because it makes direct HTTP requests, but the IDE extension (running in a browser-like environment) was being blocked by this restriction.

### Solution
Changed the ProxyPal configuration to set `restrict-management-to-localhost: false` for the ampcode section. This allows both:
- ✅ AMP CLI (direct HTTP requests)  
- ✅ AMP IDE extension (browser-based requests from VSCode)

to work simultaneously with ProxyPal.

### Changes Made
- Modified `src-tauri/src/lib.rs` line 1054
- Changed `restrict-management-to-localhost` from `true` to `false`

**Commit:** f9f8a49

The fix will be included in the next release. Both AMP CLI and IDE extension should now work without any "Invalid API key" errors! 🎉

**Branch:** dev

**Comment by damianpdr** [comment]
Tried newest version Version 0.1.24 (0.1.24) @heyhuynhgiabuu 

I reset IDE, uninstall extension amp and install again in vscode set up url to http://localhost:8317 and still see the same error.
Amp CLI still works fine.

<img width="696" height="266" alt="Image" src="https://github.com/user-attachments/assets/669e2ed1-1c2a-4136-8b19-cbdd4e54255e" /> 

<img width="716" height="568" alt="Image" src="https://github.com/user-attachments/assets/aa870a31-7270-43ec-98d6-64501cd781db" /> 

<img width="1542" height="406" alt="Image" src="https://github.com/user-attachments/assets/5157eb0e-6542-49cc-bf93-d6b5b1cb5965" />

**Comment by heyhuynhgiabuu** [comment]
You can try downloading the latest version again to check if everything has resolved this issue.

https://github.com/heyhuynhgiabuu/proxypal/releases/tag/v0.1.30

**Comment by KiraKas-Tr** [comment]
The URL in the extension must include /v1. The API key in ProxyPal is the AMP API key, while in the extension it should be proxypal-local.

**Comment by tquoc229** [comment]
Mình thử với phiên bảng 0.1.37 vẫn bị lỗi Invalid API Key. Đã thử với url: http://localhost:8317 và http://localhost:8317/v1 đều bị lỗi.

<img width="343" height="270" alt="Image" src="https://github.com/user-attachments/assets/594625ab-2e99-4b1e-9cef-785732a281e1" />

<img width="361" height="415" alt="Image" src="https://github.com/user-attachments/assets/00810549-6915-4a93-a97e-eca39592b0f2" />

<img width="1366" height="697" alt="Image" src="https://github.com/user-attachments/assets/fd9bc82a-dbb3-46e5-bbf0-d5a59ceadbe6" />

<img width="1366" height="697" alt="Image" src="https://github.com/user-attachments/assets/11091871-cca9-4c49-817e-f30485fa3ba0" />

<img width="1366" height="697" alt="Image" src="https://github.com/user-attachments/assets/3a3c032c-6495-4024-9046-2b422674e8e3" />

**Comment by KiraKas-Tr** [comment]
> Mình thử với phiên bảng 0.1.37 vẫn bị lỗi Invalid API Key. Đã thử với url: http://localhost:8317 và http://localhost:8317/v1 đều bị lỗi.
> 
> <img alt="Image" width="343" height="270" src="https://private-user-images.githubusercontent.com/78257/525975139-594625ab-2e99-4b1e-9cef-785732a281e1.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjU1NTkyMzksIm5iZiI6MTc2NTU1ODkzOSwicGF0aCI6Ii83ODI1Ny81MjU5NzUxMzktNTk0NjI1YWItMmU5OS00YjFlLTljZWYtNzg1NzMyYTI4MWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjEyVDE3MDIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljMWNlZDFlZjJmYTkwY2Q4ZWNmODlmOGQzMmY1OWYyYThhNzY1Y2M5OTZjN2ZiN2M5ZGNiOTJmNTNmMWIwNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KDTMytqu1Rwa_xbOmH6wjiEYGJMdmzOFWac7VPX_m4o"> <img alt="Image" width="361" height="415" src="https://private-user-images.githubusercontent.com/78257/525973798-00810549-6915-4a93-a97e-eca39592b0f2.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjU1NTkyMzksIm5iZiI6MTc2NTU1ODkzOSwicGF0aCI6Ii83ODI1Ny81MjU5NzM3OTgtMDA4MTA1NDktNjkxNS00YTkzLWE5N2UtZWNhMzk1OTJiMGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjEyVDE3MDIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ZjIxMDU1YTZiZWEwNTQ4ODgxZjAyOTZlYjZhOTI2MDE4ZmJiOTVjNGVkZDQ5NjgyYzgxMDI4YThkMWE1ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Avt9zSQEPSKBwP7UtTSBfDAMwn5s8ufURYMrWdI4hEs"> <img alt="Image" width="1366" height="697" src="https://private-user-images.githubusercontent.com/78257/525974063-fd9bc82a-dbb3-46e5-bbf0-d5a59ceadbe6.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjU1NTkyMzksIm5iZiI6MTc2NTU1ODkzOSwicGF0aCI6Ii83ODI1Ny81MjU5NzQwNjMtZmQ5YmM4MmEtZGJiMy00NmU1LWJiZjAtZDVhNTljZWFkYmU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjEyVDE3MDIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMTRlYmJhNzhiNjQ3MWViODFiMjliOTJlZTMyMzVkYWJmNGMzZTllYzE4ODFiZjI0NTZlODZkOTU1NzVmZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Tn53mn_4Z-V2Cb9bhvmY3lDU_vFl4MvMRRBZByngI2I"> <img alt="Image" width="1366" height="697" src="https://private-user-images.githubusercontent.com/78257/525974211-11091871-cca9-4c49-817e-f30485fa3ba0.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjU1NTkyMzksIm5iZiI6MTc2NTU1ODkzOSwicGF0aCI6Ii83ODI1Ny81MjU5NzQyMTEtMTEwOTE4NzEtY2NhOS00YzQ5LTgxN2UtZjMwNDg1ZmEzYmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjEyVDE3MDIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkOTI5NzMyYzhkM2E5Y2UyYWIwNDdiMzQzZGE3YTAyZDZjZmRkNzY4Y2U1ZWI2ZjhjYWExNzZjNDI3MWM5YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YlkU7pQVhBP5mZKRH_hlbC6z3Czg9Ryowq5k-tkG9cc"> <img alt="Image" width="1366" height="697" src="https://private-user-images.githubusercontent.com/78257/525977841-3a3c032c-6495-4024-9046-2b422674e8e3.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjU1NTkyMzksIm5iZiI6MTc2NTU1ODkzOSwicGF0aCI6Ii83ODI1Ny81MjU5Nzc4NDEtM2EzYzAzMmMtNjQ5NS00MDI0LTkwNDYtMmI0MjI2NzRlOGUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjEyVDE3MDIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3N2QxYjA2ZTZhNmY4YjUzYmQ0N2U2NGYzNDA5NTk3NmZhY2QwNmM3YjliM2MxZjIyMjMyNTM4ODgxYThiM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NTNOSscBqGLjidUo_BpWo5eMsLf502NAUnKini3f2vU">

key trong proxypal sẽ là key lấy từ website của amp, còn apikey trong extenstion sẽ là proxypal-local url thì là phải có v1

**Comment by tquoc229** [comment]
> key trong proxypal sẽ là key lấy từ website của amp, còn apikey trong extenstion sẽ là proxypal-local url thì là phải có v1

Cảm ơn bạn mình làm được rồi. 

<img width="291" height="199" alt="Image" src="https://github.com/user-attachments/assets/b59c4546-e128-44e8-8adf-5b23cc1609de" />
