### ISSUE TITLE
Cloudflare Tunnel not working through the application

### ISSUE THREAD

**Issue by mkarolczyk** [heyhuynhgiabuu/proxypal#86]
I have configured a Cloudflare Tunnel in the application to expose the local ProxyAI service (Port 8317). The tunnel is enabled (green
   toggle) but shows a perpetual "Retrying in 5s..." status and never successfully establishes a connection.

   Expected behavior: The Cloudflare Tunnel should successfully connect and expose the local API via Cloudflare's infrastructure, showing
   a connected status with a public URL.

   Actual behavior: The tunnel remains stuck in a retry loop, displaying "Port 8317 • Retrying in 5s..." and never establishing a
   connection.

   Important note: When using the cloudflared command directly from the terminal (following Cloudflare's official tunnel setup), the
   tunnel connects without any issues. This confirms that:
   •  The cloudflared binary is properly installed
   •  The tunnel token is valid
   •  Network connectivity to Cloudflare's services is working
   •  The local service on port 8317 is accessible

   Conclusion: The issue appears to be specific to how the application spawns/manages the Cloudflare Tunnel process, rather than a
   configuration or network problem.

   Steps to reproduce:
   1. Install cloudflared on the system
   2. Create a tunnel in Cloudflare Zero Trust Dashboard
   3. Copy the tunnel token
   4. Add the tunnel in the application with port 8317
   5. Enable the tunnel
   6. Observe the "Retrying in 5s..." status that persists indefinitely

   Troubleshooting attempted:
   •  Verified tunnel works via direct cloudflared command
   •  Restarted the application
   •  Recreated the tunnel configuration

   Question: Are there any logs available that show why the tunnel connection is failing when launched through the application?

<img width="1314" height="852" alt="Image" src="https://github.com/user-attachments/assets/e4296914-1c6f-4c7e-a999-effbf4e46cd1" />

**Comment by heyhuynhgiabuu** [comment]
Fixed in commit.

**Root cause:** The `cloudflared tunnel run` command was missing the `--url` argument to specify which local port to expose. The tunnel token alone tells Cloudflare *which* tunnel to use, but not *what* to tunnel to.

**Fix:** Added `--url http://localhost:<port>` to the cloudflared command, using the configured local port (e.g., 8317).

Before:
```
cloudflared tunnel run --token <token>
```

After:
```
cloudflared tunnel run --token <token> --url http://localhost:8317
```

Please update to the next release and test again.

**Comment by mkarolczyk** [comment]
Still not working. The same problem after update.

**Comment by heyhuynhgiabuu** [comment]
**Fixed in v0.3.39**

The issue was that ProxyPal was incorrectly passing `--url` flag with token-based tunnels. For **remotely-managed tunnels** (with token from Cloudflare dashboard), the ingress rules are configured **in the Cloudflare Zero Trust dashboard**, not via CLI flags.

**Please ensure your tunnel has a Public Hostname configured:**

1. Go to [Cloudflare Zero Trust Dashboard](https://one.dash.cloudflare.com/) → **Networks** → **Tunnels**
2. Select your tunnel → **Public Hostname** tab
3. Add a hostname with:
   - **Service Type:** `HTTP`
   - **URL:** `localhost:8317` (or your proxy port)

**Changes in v0.3.39:**
- Removed `--url` flag for token-based tunnels (ingress configured in dashboard)
- Added quick tunnel support (no token) with `--url` flag
- Improved connection status detection
- Updated UI with detailed setup instructions and warning note

Please update to v0.3.39 and let us know if the issue persists.

**Comment by mkarolczyk** [comment]
Still not working, my configuration CloudFlare is OK. Using the command displayed by CloudFlare works correctly.

<img width="3036" height="892" alt="Image" src="https://github.com/user-attachments/assets/3cb04f0f-3b98-4716-ba1a-54e68f0b5d86" />

<img width="2726" height="796" alt="Image" src="https://github.com/user-attachments/assets/42ad4570-c88b-49c7-8c01-133cecc31b7e" />

**Comment by heyhuynhgiabuu** [comment]
@mkarolczyk The fix is in **v0.3.39** which was just released. Please download the latest version from [Releases](https://github.com/heyhuynhgiabuu/proxypal/releases/tag/v0.3.39).

The issue was that the previous version was using an incorrect command:
```bash
# Old (wrong)
cloudflared tunnel run --token <token> --url http://localhost:8317

# New (correct) 
cloudflared tunnel run --token <token>
```

For token-based tunnels, the `--url` flag should NOT be used because the ingress rules are configured in the Cloudflare dashboard.

After updating to v0.3.39, please:
1. Disable the tunnel
2. Re-enable the tunnel
3. Check if it connects

Let me know if you still have issues after updating!

**Comment by heyhuynhgiabuu** [comment]
I've rewritten the Cloudflare tunnel manager with a proper fix:

**Issues found:**
1. The previous code had a blocking async flow that caused unnecessary retries
2. Log detection patterns weren't matching cloudflared's actual output format

**Fixes in upcoming v0.3.40:**
- Rewrote the tunnel manager with proper async handling
- Added connection state tracking to differentiate "never connected" vs "connection lost"
- Smart retry: max 3 attempts if can't connect, unlimited if connection drops unexpectedly
- Better log parsing for cloudflared's actual output format

Your Cloudflare configuration looks correct (Service: `http://localhost:8317`). The issue was on ProxyPal's side with how we managed the cloudflared process.

Will release v0.3.40 shortly - please test after updating!

**Comment by mkarolczyk** [comment]
The problem persists. I even attempted to remove the tunnel and add it again. It keeps saying Retrying...

**Comment by mkarolczyk** [comment]
<img width="2442" height="768" alt="Image" src="https://github.com/user-attachments/assets/560b1d4d-95d1-41c8-8b47-573b0392a51f" />

<img width="1266" height="1104" alt="Image" src="https://github.com/user-attachments/assets/487c3636-6410-4ab0-ac1c-3eaf5511aa2c" />

**Comment by heyhuynhgiabuu** [comment]
**Fixed in v0.3.41** 🎉

Found the real issue! The error message **"cloudflared not found"** indicates that ProxyPal couldn't locate the `cloudflared` binary.

**Root cause:** GUI apps on macOS don't inherit the terminal's PATH environment variable, so `cloudflared` installed via Homebrew wasn't being found - even though it works from your terminal.

**Fix in v0.3.41:** ProxyPal now checks common installation paths:
- `/opt/homebrew/bin/cloudflared` (macOS Apple Silicon - Homebrew)
- `/usr/local/bin/cloudflared` (macOS Intel, Linux)
- `/usr/bin/cloudflared`, `/snap/bin/cloudflared` (Linux)
- `~/.local/bin/cloudflared` (user local)

Please update to [v0.3.41](https://github.com/heyhuynhgiabuu/proxypal/releases/tag/v0.3.41) and try again!

**Comment by mkarolczyk** [comment]
It's working now, thank you!

<img width="1238" height="1026" alt="Image" src="https://github.com/user-attachments/assets/d3c7890e-d5f9-4229-a158-805b6da4cddf" />

**Comment by heyhuynhgiabuu** [comment]
If you still have this problem, just ping me. Thank you
