### ISSUE TITLE
Bug: Tabs fail with 401 Unauthorized after changing Management API Key

### ISSUE THREAD

**Issue by mkarolczyk** [heyhuynhgiabuu/proxypal#89]
After updating the Management API Key in settings, certain tabs (e.g., Logs) stop working and display authentication errors. The application appears to cache the old key and doesn't refresh it across all components.

  Steps to Reproduce

  1. Open the application settings
  2. Change the "Management API Key" to a new value (e.g., Proxypal-mgmt-key1)
  3. Save the settings
  4. Navigate to the Logs tab (or other management-related tabs)

  Expected Behavior

  All tabs should work correctly with the newly configured Management API Key.

  Actual Behavior

  The Logs tab shows "No Logs" and displays an error toast:
  Failed to load logs: Failed to get logs: 401 Unauthorized - {"error":"invalid management key"}

  Models not visible.

  Possible Cause

  The new Management API Key is not being propagated to all API clients/services after the settings change. Some components may be using a cached/stale key value.

  Environment

  - Application version: Version 0.3.39
  - OS: MacOS 26.2

<img width="1594" height="1256" alt="Image" src="https://github.com/user-attachments/assets/c0b59a86-2aa8-48af-b3bb-8435d59f2b5a" />

<img width="1216" height="522" alt="Image" src="https://github.com/user-attachments/assets/c67e09c7-bc37-4e70-a579-6029e7dd1fef" />

<img width="1234" height="614" alt="Image" src="https://github.com/user-attachments/assets/4f8eaac9-1f6a-45d3-bc63-f71a5a6ca83b" />

**Comment by mkarolczyk** [comment]
One problem may be changing the first letter in the key to UPPERCASE.

**Comment by heyhuynhgiabuu** [comment]
**Fixed in v0.3.40**

The issue was that when you change the Management API Key in ProxyPal settings, the running CLIProxyAPI proxy still had the OLD key configured. ProxyPal then used the new key to call management APIs, but CLIProxyAPI rejected it with 401 Unauthorized.

**Fixes in v0.3.40:**
- **Auto-restart proxy** - When you change the Management API Key, ProxyPal now automatically restarts the proxy to apply the new key
- **UI warning** - Added a note under the Management API Key field explaining that changes require a proxy restart

Please update to [v0.3.40](https://github.com/heyhuynhgiabuu/proxypal/releases/tag/v0.3.40) and let us know if you still have issues!

**Comment by mkarolczyk** [comment]
The model list is still broken, and the Droid reconfiguration action (and probably others as well) is not working.

<img width="1348" height="1074" alt="Image" src="https://github.com/user-attachments/assets/8bf94b32-494a-4ae9-9e24-7bd8d19e4e4f" />

**Comment by heyhuynhgiabuu** [comment]
@mkarolczyk Thanks for the follow-up. A few questions to help debug:

1. **Which version are you on?** Please check in Settings or About - v0.3.40 has the auto-restart fix.

2. **Did you see the toast messages?** When you change the Management API Key, you should see:
   - "Restarting proxy to apply new management key..."
   - "Proxy restarted with new management key"

3. **Is the proxy indicator showing as running?** (Green dot on Dashboard)

**Workaround to try now:**
1. Change your Management API Key to a new value
2. Manually stop the proxy (toggle off on Dashboard)
3. Wait 2-3 seconds
4. Start the proxy again (toggle on)
5. Check if Logs/Models tabs work now

If the workaround works but auto-restart doesn't, there might be a timing issue I need to fix.

Also, please update to **v0.3.41** which has additional fixes - this might resolve the issue.

**Comment by mkarolczyk** [comment]
Everything restarted nicely after changing the key, the only problem is with this tab (at least that's what I noticed). Previously, there was a similar problem in the logs tab, but recent versions have fixed it.

Restarting the proxy / exclusively and enabling the application does not help.

I currently have version: v0.3.41

<img width="1332" height="1082" alt="Image" src="https://github.com/user-attachments/assets/cd086527-6bfb-4a5f-b019-04fac3df00a9" />

**Comment by heyhuynhgiabuu** [comment]
**Fixed in v0.3.42** ✅

Found the root cause - the health check was **hardcoded** to use `"proxypal-local"` instead of reading the actual `proxyApiKey` from config. When you changed the key, the health check still sent the old hardcoded value and failed authentication.

**Fixes in v0.3.42:**
- Health check now reads `proxyApiKey` from config
- Management key change with auto-restart works correctly
- Added 500ms delay before restart to ensure config file is flushed

Both Proxy API Key and Management API Key changes now work properly - providers stay online after changing either key.

Please update to [v0.3.42](https://github.com/heyhuynhgiabuu/proxypal/releases/tag/v0.3.42)!

**Comment by mkarolczyk** [comment]
Still model list is empty. Nothing helps, neither changing the key nor restarting the proxy.

<img width="1194" height="960" alt="Image" src="https://github.com/user-attachments/assets/2f2e658d-751b-47ff-829c-dd0247056bda" />

**Comment by mkarolczyk** [comment]
On click Reconfigure:

<img width="1476" height="1208" alt="Image" src="https://github.com/user-attachments/assets/871a817b-df34-4f15-abfc-1f4a798058f2" />

**Comment by heyhuynhgiabuu** [comment]
Can you try again on latest version please?

**Comment by mkarolczyk** [comment]
The same problem persists, I cannot see the list of models in the application and I cannot reconfigure Factory or other CLIs. Error 401 appears on this tab.

Perhaps there is a hardcoded key somewhere in this tab?

I always test on the current version, now I have: 0.3.42

**Comment by heyhuynhgiabuu** [comment]
Found another hardcoded key! 🔍

**Root cause:** The `/v1/models` endpoint was hardcoded to use `Bearer proxypal-local` instead of reading the actual `proxy_api_key` from config.

**Fixed in commit 5837ee7** - The models list should now work correctly after changing the Proxy API Key.

This will be in the next release. @mkarolczyk please test once v0.3.43 is available!

**Comment by mkarolczyk** [comment]
It works, thank you!
